name: New project initialization

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
        description: "Name of the project to be created"
      include-readme:
        required: true
        type: string
        description: "whether to add readme file or not"
      include-gitignore:
        required: true
        type: string
        description: "whether to add gitignore file or not"        
      include-codeowners:
        required: true
        type: string
        description: "whether to add codeowners file or not" 
      include-terraform:
        required: true
        type: string
        description: "whether to add terraform related files or not"         

jobs:
  new-project-initialization:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Git setup
        run: |
          git config --global user.name "khader-github-actions"
          git config --global user.email "khader-github-actions@abc.com"

      - name: Go setup
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          
      - name: Create go new project folder
        run: |
          mkdir -p ${{ inputs.project-name }}
          cd ${{ inputs.project-name }}
          touch main.go
          go mod init ${{ inputs.project-name }}
          go mod tidy
          cd ..

      - name: Create README file
        if: ${{ inputs.include-readme == 'yes' }}
        run: |
          touch ${{ inputs.project-name }}/README.md

      - name: Create .gitignore file
        if: ${{ inputs.include-gitignore == 'yes' }}
        run: |
          touch ${{ inputs.project-name }}/.gitignore

      - name: Create codeowners file
        if: ${{ inputs.include-codeowners == 'yes' }}
        run: |
          touch ${{ inputs.project-name }}/CODEOWNERS
          
      - name: Create terraform code files
        if: ${{ inputs.include-terraform == 'yes' }}
        run: |
          mkdir -p terraform/layers/application/${{ inputs.project-name }}
          touch terraform/layers/application/${{ inputs.project-name }}/main.tf
          touch terraform/layers/application/${{ inputs.project-name }}/vars.tf
          touch terraform/layers/application/${{ inputs.project-name }}/versions.tf
          mkdir -p terraform/layers/service/${{ inputs.project-name }}
          touch terraform/layers/service/${{ inputs.project-name }}/main.tf
          touch terraform/layers/service/${{ inputs.project-name }}/vars.tf
          touch terraform/layers/service/${{ inputs.project-name }}/versions.tf          
          
      # Runs a set of commands using the runners shell
      - name: Commit and Push Changes
        run: |
          git status
          git add ${{ inputs.project-name }}*
          git add terraform/layers/application/${{ inputs.project-name }}*
          git add terraform/layers/service/${{ inputs.project-name }}*
          git commit -m "${{ inputs.project-name }} intialization"
          git push
